# Generated by Django 3.0.6 on 2020-06-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0002_auto_20200528_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ceshi',
            new_name='Test',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='name_title',
            new_name='name',
        ),
    ]
