# Generated by Django 3.0.6 on 2020-06-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0003_auto_20200603_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_title', models.CharField(max_length=10000)),
                ('follower_count', models.IntegerField()),
                ('relation', models.IntegerField()),
                ('detail', models.CharField(max_length=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
