# Generated by Django 3.0.6 on 2020-06-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0004_auto_20200603_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_test',
            name='detail',
            field=models.CharField(max_length=60000),
        ),
    ]
